REVOKE CREATE ON SCHEMA public FROM PUBLIC;
DO
$$BEGIN
IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'reactornet') THEN
    EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE status FROM reactornet';
    EXECUTE 'REVOKE CONNECT ON DATABASE reactornet FROM reactornet';
END IF;
END$$;
DROP USER IF EXISTS reactornet;
CREATE USER reactornet WITH PASSWORD 'KK1BYhK5pjamf3xDURp1xVr0oWg0waxV';
ALTER USER reactornet SET statement_timeout='10s';
GRANT CONNECT ON DATABASE reactornet TO reactornet;

DROP TABLE IF EXISTS status;
CREATE TABLE status(
  id SERIAL PRIMARY KEY,
  key VARCHAR(255) NOT NULL,
  value VARCHAR(255) NOT NULL,
  unit VARCHAR(255) NOT NULL,
  details TEXT NOT NULL
);

GRANT SELECT ON status TO reactornet;
INSERT INTO status
(key, value, unit, details)
VALUES ('emergency_scram_code', 'SCRAM-QYZX3ZMNXVMNKT52YOVNOIAJLWGFV3YF', 'string', 'The current SCRAM code.');
INSERT INTO status
(key, value, unit, details)
VALUES ('reactor_temperature', '169', '°C', 'The reactor temperature indicates the temperature of the coolant flowing through the reactor. If the temperature exceeds the maximum value, it can lead to a loss of coolant or damage to the reactor, potentially resulting in a loss of control over the nuclear reaction and a release of radiation.');
INSERT INTO status
(key, value, unit, details)
VALUES ('reactor_pressure', '81', 'BAR', 'The reactor temperature indicates the temperature of the coolant flowing through the reactor. If the temperature exceeds the maximum value, it can lead to a loss of coolant or damage to the reactor, potentially resulting in a loss of control over the nuclear reaction and a release of radiation.');
INSERT INTO status
(key, value, unit, details)
VALUES ('reactor_output', '102', 'MW', 'The power output indicates the amount of electricity being generated by the reactor. If the power output exceeds the maximum value, it can lead to a loss of control over the nuclear reaction, potentially resulting in a release of radiation.');
INSERT INTO status
(key, value, unit, details)
VALUES ('reactor_coolant_flow', '20197', 'm³/hr', 'The reactor coolant flow rate indicates the rate at which coolant is flowing through the reactor. If the flow rate is too low, it can lead to a loss of cooling and a buildup of heat, potentially resulting in damage to the reactor. If the flow rate is too high, it can lead to a loss of efficiency and increased wear and tear on the reactor components.');
INSERT INTO status
(key, value, unit, details)
VALUES ('reactor_neutron_flux', '55756694836', 'n/cm²/s', 'The neutron flux indicates the density of neutrons within the reactor, which is a measure of the rate of nuclear fission. If the neutron flux exceeds the maximum value, it can lead to a loss of control over the nuclear reaction and a release of radiation.');
INSERT INTO status
(key, value, unit, details)
VALUES ('reactor_radiation_level', '5', 'µSv/hr', 'The radiation levels indicate the radiation levels within the reactor, which must be carefully monitored to ensure the safety of personnel working in the area. If the radiation levels exceed the maximum value, it can pose a serious risk to the health and safety of personnel and require immediate action to mitigate the release of radiation.');
INSERT INTO status
(key, value, unit, details)
VALUES ('turbine_speed', '3387', 'RPM', 'The turbine speed indicates the speed at which the steam turbine is rotating, which is directly related to the amount of electricity being generated. If the turbine speed exceeds the maximum value, it can lead to damage to the turbine blades or other components due to the high stress and centrifugal forces. This can result in a decrease in the efficiency and output of the turbine or a complete failure of the system.');
INSERT INTO status
(key, value, unit, details)
VALUES ('turbine_inlet_pressure', '113', 'BAR', 'The turbine inlet pressure indicates the pressure of the steam entering the turbine from the reactor, which is used to drive the turbine blades. If the turbine inlet pressure exceeds the maximum value, it can lead to damage or failure of the turbine blades due to the high pressure and stress. This can result in a decrease in the efficiency and output of the turbine or a complete failure of the system.');
INSERT INTO status
(key, value, unit, details)
VALUES ('turbine_inlet_temperature', '423', '°C', 'The turbine inlet temperature indicates the temperature of the steam entering the turbine, which affects the efficiency and performance of the turbine. If the turbine inlet temperature exceeds the maximum value, it can lead to damage or failure of the turbine blades due to the high temperature and thermal stress. This can result in a decrease in the efficiency and output of the turbine or a complete failure of the system.');
INSERT INTO status
(key, value, unit, details)
VALUES ('turbine_exhaust_pressure', '16', 'BAR', 'The turbine exhaust pressure indicates the pressure of the steam leaving the turbine and entering the condenser, which is used to recycle the steam and maintain the cycle of the power plant. If the turbine exhaust pressure exceeds the maximum value, it can lead to a loss of efficiency and performance of the turbine, as well as potential damage or failure of the condenser and other components.');
INSERT INTO status
(key, value, unit, details)
VALUES ('turbine_exhaust_temperature', '50', '°C', 'The turbine exhaust temperature indicates the temperature of the steam leaving the turbine and entering the condenser, which affects the efficiency and performance of the turbine. If the turbine exhaust temperature exceeds the maximum value, it can lead to a loss of efficiency and performance of the turbine, as well as potential damage or failure of the condenser and other components.');
INSERT INTO status
(key, value, unit, details)
VALUES ('turbine_generator_voltage', '11265', 'V', 'The generator voltage indicates the voltage output of the generator, which is used to supply electricity to the power grid. If the generator voltage exceeds the maximum value, it can lead to damage or failure of the generator or other components due to the high voltage and electrical stress. This can result in a loss of power generation or a complete failure of the system.');
INSERT INTO status
(key, value, unit, details)
VALUES ('turbine_generator_current', '1856', 'A', 'The generator current indicates the current output of the generator, which is directly related to the amount of electricity being generated. If the generator current exceeds the maximum value, it can lead to damage or failure of the generator or other components due to the high current and electrical stress. This can result in a loss of power generation or a complete failure of the system.');
INSERT INTO status
(key, value, unit, details)
VALUES ('radiation_levels', '338', 'µSv/h', 'This parameter refers to the amount of ionizing radiation present in a particular area, measured in microsieverts per hour (µSv/h). When the radiation levels exceed the maximum value, it could pose a risk to the health and safety of the workers and the public, and emergency measures such as evacuation, sheltering, or protective equipment may need to be implemented.');
INSERT INTO status
(key, value, unit, details)
VALUES ('radiation_gas_concentration', '85530', 'Bq/m³', 'This parameter refers to the concentration of radioactive gases, such as tritium, krypton, and xenon, in the air, measured in becquerels per cubic meter (Bq/m³). When the concentration exceeds the maximum value, it could indicate a potential leak or release of radioactive material, and measures to contain and control the release may need to be taken.');
INSERT INTO status
(key, value, unit, details)
VALUES ('radiation_liquid_concentration', '3729', 'Bq/L', 'This parameter refers to the concentration of radioactive liquids, such as wastewater or cooling water, measured in becquerels per liter (Bq/L). When the concentration exceeds the maximum value, it could indicate a potential leak or release of radioactive material into the environment, and measures to contain and treat the contaminated liquid may need to be taken.');
INSERT INTO status
(key, value, unit, details)
VALUES ('radiation_contamination_levels', '2425', 'Bq/L', 'This parameter refers to the level of radioactive contamination on surfaces, such as floors, walls, equipment, or clothing, measured in becquerels per square meter (Bq/m²). When the contamination levels exceed the maximum value, it could indicate a potential risk of external or internal exposure to radioactive material, and measures to decontaminate the affected surfaces or equipment may need to be taken.');
INSERT INTO status
(key, value, unit, details)
VALUES ('radiation_danger_level', '1', 'Sv/h', 'This parameter refers to the threshold radiation level at which emergency measures, such as evacuation or sheltering, need to be taken, measured in millisieverts per hour (mSv/h). When the radiation levels exceed the emergency threshold, it could pose an immediate danger to the health and safety of the workers and the public, and prompt and effective emergency measures should be implemented.');