version: "3.7"

services:
  website:
    image: 3llobo/cryptowebsite:latest
    user: nobody
    ports:
      - "8080:8080"
    volumes:
      - /../../data/cryptoscope:/data:ro
    deploy:
      restart_policy: {}
      resources:
        limits:
          cpus: '0.8'
          memory: 128M
